#############################################################################
# Makefile for building: elin
# Generated by qmake (2.01a) (Qt 4.8.7) on: Sun Nov 14 07:37:43 2021
# Project:  newAfc.pro
# Template: app
# Command: /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/qmake -spec ../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ -o Makefile newAfc.pro
#############################################################################

####### Compiler, tools and options

CC            = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/arm-linux-gnueabihf-gcc
CXX           = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/arm-linux-gnueabihf-g++
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -I/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr//include -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -std=gnu++98 -I/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr//include -std=c++11 -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ -I. -I../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtCore -I../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtNetwork -I../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtGui -I../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include/QtSql -I../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/include -IQtSerialPort -Icrypto -IQOnScreenKeyboard -I. -I.
LINK          = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/arm-linux-gnueabihf-g++
LFLAGS        = -L/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr//lib -lEGL -lGLESv2 -lUMP -Wl,-O1
LIBS          = $(SUBLIBS)  -L/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib /home/farzad/work/backups/20210316/src/crypto/libcrypto.a /home/farzad/work/backups/20210316/src/QOnScreenKeyboard/libQOnScreenKeyboard.a -lQtSql -L/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot//usr/lib -L/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib -lpq -rdynamic -lmysqlclient_r -lz -lcrypt -lnsl -lm -lodbc -lQtGui -ldirectfb -lfusion -ldirect -lEGL -lQtNetwork -lQtCore -lpthread 
AR            = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/arm-linux-gnueabihf-ar cqs
RANLIB        = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/arm-linux-gnueabihf-ranlib
QMAKE         = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = /home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/arm-linux-gnueabihf-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		QtSerialPort/qserialport.cpp \
		QtSerialPort/qserialportinfo.cpp \
		QtSerialPort/qserialportinfo_unix.cpp \
		QtSerialPort/qserialport_unix.cpp \
		QtSerialPort/qttylocker_unix.cpp \
		DualiCardReader.cpp \
		MifareCard.cpp \
		MainWindow.cpp \
		MemoryBlock.cpp \
		DesfireCard.cpp \
		QrCode.cpp \
		HoneywellBarcodeReader.cpp \
		CityPayCard.cpp \
		Cryptography.cpp \
		CityPaySam.cpp \
		Utilities.cpp \
		CityWayCard.cpp \
		CityPayTransactionLog.cpp \
		CityPaySettlementManager.cpp \
		Scu.cpp \
		ActivityManager.cpp \
		ParameterManager.cpp \
		MetroBusiness.cpp \
		GateController.cpp \
		GpioSunXi.cpp \
		BuzzerController.cpp \
		PanelWidget.cpp \
		QFocusableLineEdit.cpp \
		QrTicket.cpp \
		QrDbManager.cpp \
		QrServerManager.cpp \
		QrKeyStore.cpp moc_MainWindow.cpp \
		moc_HoneywellBarcodeReader.cpp \
		moc_Scu.cpp \
		moc_ParameterManager.cpp \
		moc_MetroBusiness.cpp \
		moc_GateController.cpp \
		moc_PanelWidget.cpp \
		moc_QFocusableLineEdit.cpp \
		moc_QrServerManager.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		qserialport.o \
		qserialportinfo.o \
		qserialportinfo_unix.o \
		qserialport_unix.o \
		qttylocker_unix.o \
		DualiCardReader.o \
		MifareCard.o \
		MainWindow.o \
		MemoryBlock.o \
		DesfireCard.o \
		QrCode.o \
		HoneywellBarcodeReader.o \
		CityPayCard.o \
		Cryptography.o \
		CityPaySam.o \
		Utilities.o \
		CityWayCard.o \
		CityPayTransactionLog.o \
		CityPaySettlementManager.o \
		Scu.o \
		ActivityManager.o \
		ParameterManager.o \
		MetroBusiness.o \
		GateController.o \
		GpioSunXi.o \
		BuzzerController.o \
		PanelWidget.o \
		QFocusableLineEdit.o \
		QrTicket.o \
		QrDbManager.o \
		QrServerManager.o \
		QrKeyStore.o \
		moc_MainWindow.o \
		moc_HoneywellBarcodeReader.o \
		moc_Scu.o \
		moc_ParameterManager.o \
		moc_MetroBusiness.o \
		moc_GateController.o \
		moc_PanelWidget.o \
		moc_QFocusableLineEdit.o \
		moc_QrServerManager.o \
		qrc_res.o
DIST          = ../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/unix.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/linux.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base-unix.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-base.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-unix.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/qws.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qconfig.pri \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_functions.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_config.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/exclusive_builds.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_pre.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/release.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_post.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/shared.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/warn_on.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/unix/thread.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/moc.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/resources.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/uic.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/yacc.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/lex.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/include_source_dir.prf \
		newAfc.pro
QMAKE_TARGET  = elin
DESTDIR       = 
TARGET        = elin

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_PanelWidget.h ui_MainWindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: newAfc.pro  ../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++/qmake.conf ../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/unix.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/linux.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base-unix.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-base.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-unix.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/qws.conf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qconfig.pri \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_functions.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_config.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/exclusive_builds.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_pre.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/release.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_post.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/shared.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/warn_on.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/unix/thread.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/moc.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/resources.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/uic.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/yacc.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/lex.prf \
		../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/include_source_dir.prf \
		/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtSql.prl \
		/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtCore.prl \
		/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtGui.prl \
		/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ -o Makefile newAfc.pro
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/unix.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/linux.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/gcc-base-unix.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-base.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/g++-unix.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/common/qws.conf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qconfig.pri:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_functions.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt_config.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/exclusive_builds.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_pre.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/release.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/default_post.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/shared.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/warn_on.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/qt.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/unix/thread.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/moc.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/resources.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/uic.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/yacc.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/lex.prf:
../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/features/include_source_dir.prf:
/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtSql.prl:
/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtCore.prl:
/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtGui.prl:
/home/farzad/Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../../Desktop/buildroot-2017.05/output/host/usr/arm-buildroot-linux-gnueabihf/sysroot/usr/mkspecs/qws/linux-arm-g++ -o Makefile newAfc.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/elin1.0.0 || $(MKDIR) .tmp/elin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/elin1.0.0/ && $(COPY_FILE) --parents QtSerialPort/qserialport.h QtSerialPort/qserialportglobal.h QtSerialPort/qserialportinfo.h QtSerialPort/qserialportinfo_p.h QtSerialPort/qserialport_p.h QtSerialPort/qserialport_unix_p.h QtSerialPort/qttylocker_unix_p.h CardReader.h Result.h DualiCardReader.h MifareCard.h CreditCard.h CreditCardType.h Business.h MainWindow.h MemoryBlock.h Settings.h DesfireCard.h WindowManager.h Device.h BarcodeReader.h Barcode.h BarcodeType.h QrCode.h HoneywellBarcodeReader.h CityPayCard.h Cryptography.h CityPaySam.h Utilities.h CityWayCard.h TransactionLog.h CityPayTransactionLog.h SettlementManager.h CityPaySettlementManager.h Scu.h ActivityManager.h ParameterManager.h MetroBusiness.h GateController.h GpioSunXi.h BuzzerController.h PanelWidget.h QFocusableLineEdit.h QrDbManager.h QrTicket.h QrServerManager.h QrKeyStore.h .tmp/elin1.0.0/ && $(COPY_FILE) --parents Resources/res.qrc .tmp/elin1.0.0/ && $(COPY_FILE) --parents main.cpp QtSerialPort/qserialport.cpp QtSerialPort/qserialportinfo.cpp QtSerialPort/qserialportinfo_unix.cpp QtSerialPort/qserialport_unix.cpp QtSerialPort/qttylocker_unix.cpp DualiCardReader.cpp MifareCard.cpp MainWindow.cpp MemoryBlock.cpp DesfireCard.cpp QrCode.cpp HoneywellBarcodeReader.cpp CityPayCard.cpp Cryptography.cpp CityPaySam.cpp Utilities.cpp CityWayCard.cpp CityPayTransactionLog.cpp CityPaySettlementManager.cpp Scu.cpp ActivityManager.cpp ParameterManager.cpp MetroBusiness.cpp GateController.cpp GpioSunXi.cpp BuzzerController.cpp PanelWidget.cpp QFocusableLineEdit.cpp QrTicket.cpp QrDbManager.cpp QrServerManager.cpp QrKeyStore.cpp .tmp/elin1.0.0/ && $(COPY_FILE) --parents PanelWidget.ui MainWindow.ui .tmp/elin1.0.0/ && (cd `dirname .tmp/elin1.0.0` && $(TAR) elin1.0.0.tar elin1.0.0 && $(COMPRESS) elin1.0.0.tar) && $(MOVE) `dirname .tmp/elin1.0.0`/elin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/elin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_qserialport.cpp moc_MainWindow.cpp moc_HoneywellBarcodeReader.cpp moc_Scu.cpp moc_ParameterManager.cpp moc_MetroBusiness.cpp moc_GateController.cpp moc_PanelWidget.cpp moc_QFocusableLineEdit.cpp moc_QrServerManager.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_qserialport.cpp moc_MainWindow.cpp moc_HoneywellBarcodeReader.cpp moc_Scu.cpp moc_ParameterManager.cpp moc_MetroBusiness.cpp moc_GateController.cpp moc_PanelWidget.cpp moc_QFocusableLineEdit.cpp moc_QrServerManager.cpp
moc_qserialport.cpp: QtSerialPort/qserialportglobal.h \
		QtSerialPort/qserialport.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) QtSerialPort/qserialport.h -o moc_qserialport.cpp

moc_MainWindow.cpp: WindowManager.h \
		ActivityManager.h \
		ParameterManager.h \
		Result.h \
		Scu.h \
		Utilities.h \
		MainWindow.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) MainWindow.h -o moc_MainWindow.cpp

moc_HoneywellBarcodeReader.cpp: BarcodeReader.h \
		Device.h \
		Result.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		HoneywellBarcodeReader.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) HoneywellBarcodeReader.h -o moc_HoneywellBarcodeReader.cpp

moc_Scu.cpp: Utilities.h \
		Scu.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) Scu.h -o moc_Scu.cpp

moc_ParameterManager.cpp: Result.h \
		ParameterManager.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) ParameterManager.h -o moc_ParameterManager.cpp

moc_MetroBusiness.cpp: Business.h \
		CardReader.h \
		Device.h \
		Result.h \
		MemoryBlock.h \
		QrServerManager.h \
		ParameterManager.h \
		MetroBusiness.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) MetroBusiness.h -o moc_MetroBusiness.cpp

moc_GateController.cpp: Device.h \
		Result.h \
		GateController.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) GateController.h -o moc_GateController.cpp

moc_PanelWidget.cpp: ActivityManager.h \
		ParameterManager.h \
		Result.h \
		Scu.h \
		Utilities.h \
		PanelWidget.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) PanelWidget.h -o moc_PanelWidget.cpp

moc_QFocusableLineEdit.cpp: QFocusableLineEdit.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) QFocusableLineEdit.h -o moc_QFocusableLineEdit.cpp

moc_QrServerManager.cpp: QrServerManager.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/moc $(DEFINES) $(INCPATH) QrServerManager.h -o moc_QrServerManager.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: Resources/res.qrc \
		Resources/images/logo_metro.png \
		Resources/images/logo_mapra.png \
		Resources/images/logo_elin.png \
		Resources/images/icon_settings.png \
		Resources/images/banner.png \
		Resources/Fonts/Sahel-FD.ttf \
		Resources/Fonts/Sahel-Black-FD.ttf
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/rcc -name res Resources/res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_PanelWidget.h ui_MainWindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_PanelWidget.h ui_MainWindow.h
ui_PanelWidget.h: PanelWidget.ui \
		QFocusableLineEdit.h
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/uic PanelWidget.ui -o ui_PanelWidget.h

ui_MainWindow.h: MainWindow.ui
	/home/farzad/Desktop/buildroot-2017.05/output/host/usr/bin/uic MainWindow.ui -o ui_MainWindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainWindow.h \
		WindowManager.h \
		ActivityManager.h \
		ParameterManager.h \
		Result.h \
		Scu.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

qserialport.o: QtSerialPort/qserialport.cpp QtSerialPort/qserialport.h \
		QtSerialPort/qserialportglobal.h \
		QtSerialPort/qserialportinfo.h \
		QtSerialPort/qserialport_unix_p.h \
		QtSerialPort/qserialport_p.h \
		QtSerialPort/qt4support/qringbuffer_p.h \
		moc_qserialport.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qserialport.o QtSerialPort/qserialport.cpp

qserialportinfo.o: QtSerialPort/qserialportinfo.cpp QtSerialPort/qserialportinfo.h \
		QtSerialPort/qserialportglobal.h \
		QtSerialPort/qserialportinfo_p.h \
		QtSerialPort/qserialport.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qserialportinfo.o QtSerialPort/qserialportinfo.cpp

qserialportinfo_unix.o: QtSerialPort/qserialportinfo_unix.cpp QtSerialPort/qserialportinfo.h \
		QtSerialPort/qserialportglobal.h \
		QtSerialPort/qserialportinfo_p.h \
		QtSerialPort/qttylocker_unix_p.h \
		QtSerialPort/qserialport_unix_p.h \
		QtSerialPort/qserialport_p.h \
		QtSerialPort/qserialport.h \
		QtSerialPort/qt4support/qringbuffer_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qserialportinfo_unix.o QtSerialPort/qserialportinfo_unix.cpp

qserialport_unix.o: QtSerialPort/qserialport_unix.cpp QtSerialPort/qserialport_unix_p.h \
		QtSerialPort/qserialport_p.h \
		QtSerialPort/qserialport.h \
		QtSerialPort/qserialportglobal.h \
		QtSerialPort/qt4support/qringbuffer_p.h \
		QtSerialPort/qttylocker_unix_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qserialport_unix.o QtSerialPort/qserialport_unix.cpp

qttylocker_unix.o: QtSerialPort/qttylocker_unix.cpp QtSerialPort/qttylocker_unix_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qttylocker_unix.o QtSerialPort/qttylocker_unix.cpp

DualiCardReader.o: DualiCardReader.cpp DualiCardReader.h \
		CardReader.h \
		Device.h \
		Result.h \
		MemoryBlock.h \
		MifareCard.h \
		CreditCard.h \
		CreditCardType.h \
		DesfireCard.h \
		CityPayCard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DualiCardReader.o DualiCardReader.cpp

MifareCard.o: MifareCard.cpp MifareCard.h \
		CreditCard.h \
		Result.h \
		CreditCardType.h \
		MemoryBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MifareCard.o MifareCard.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		WindowManager.h \
		ActivityManager.h \
		ParameterManager.h \
		Result.h \
		Scu.h \
		Utilities.h \
		ui_MainWindow.h \
		PanelWidget.h \
		Settings.h \
		DualiCardReader.h \
		CardReader.h \
		Device.h \
		MemoryBlock.h \
		HoneywellBarcodeReader.h \
		BarcodeReader.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		GateController.h \
		BuzzerController.h \
		MetroBusiness.h \
		Business.h \
		QrServerManager.h \
		CityPaySam.h \
		QrKeyStore.h \
		QrDbManager.h \
		Cryptography.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

MemoryBlock.o: MemoryBlock.cpp MemoryBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MemoryBlock.o MemoryBlock.cpp

DesfireCard.o: DesfireCard.cpp DesfireCard.h \
		CreditCard.h \
		Result.h \
		CreditCardType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DesfireCard.o DesfireCard.cpp

QrCode.o: QrCode.cpp QrCode.h \
		Barcode.h \
		BarcodeType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrCode.o QrCode.cpp

HoneywellBarcodeReader.o: HoneywellBarcodeReader.cpp HoneywellBarcodeReader.h \
		BarcodeReader.h \
		Device.h \
		Result.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		QrTicket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HoneywellBarcodeReader.o HoneywellBarcodeReader.cpp

CityPayCard.o: CityPayCard.cpp CityPayCard.h \
		CreditCard.h \
		Result.h \
		CreditCardType.h \
		CardReader.h \
		Device.h \
		MemoryBlock.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CityPayCard.o CityPayCard.cpp

Cryptography.o: Cryptography.cpp Cryptography.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cryptography.o Cryptography.cpp

CityPaySam.o: CityPaySam.cpp CityPaySam.h \
		CardReader.h \
		Device.h \
		Result.h \
		MemoryBlock.h \
		Cryptography.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CityPaySam.o CityPaySam.cpp

Utilities.o: Utilities.cpp Utilities.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Utilities.o Utilities.cpp

CityWayCard.o: CityWayCard.cpp CityWayCard.h \
		CreditCard.h \
		Result.h \
		CreditCardType.h \
		CardReader.h \
		Device.h \
		MemoryBlock.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CityWayCard.o CityWayCard.cpp

CityPayTransactionLog.o: CityPayTransactionLog.cpp CityPayTransactionLog.h \
		TransactionLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CityPayTransactionLog.o CityPayTransactionLog.cpp

CityPaySettlementManager.o: CityPaySettlementManager.cpp CityPaySettlementManager.h \
		SettlementManager.h \
		TransactionLog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CityPaySettlementManager.o CityPaySettlementManager.cpp

Scu.o: Scu.cpp Scu.h \
		Utilities.h \
		Settings.h \
		ActivityManager.h \
		ParameterManager.h \
		Result.h \
		GateController.h \
		Device.h \
		QrDbManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Scu.o Scu.cpp

ActivityManager.o: ActivityManager.cpp GateController.h \
		Device.h \
		Result.h \
		Settings.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ActivityManager.o ActivityManager.cpp

ParameterManager.o: ParameterManager.cpp ParameterManager.h \
		Result.h \
		ActivityManager.h \
		BuzzerController.h \
		Utilities.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParameterManager.o ParameterManager.cpp

MetroBusiness.o: MetroBusiness.cpp MetroBusiness.h \
		Business.h \
		CardReader.h \
		Device.h \
		Result.h \
		MemoryBlock.h \
		QrServerManager.h \
		ParameterManager.h \
		WindowManager.h \
		ActivityManager.h \
		Scu.h \
		Utilities.h \
		BarcodeReader.h \
		CityPaySam.h \
		CityPayCard.h \
		CreditCard.h \
		CreditCardType.h \
		CityWayCard.h \
		QrTicket.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		QrDbManager.h \
		MifareCard.h \
		BuzzerController.h \
		GateController.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MetroBusiness.o MetroBusiness.cpp

GateController.o: GateController.cpp GateController.h \
		Device.h \
		Result.h \
		Scu.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GateController.o GateController.cpp

GpioSunXi.o: GpioSunXi.cpp GpioSunXi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GpioSunXi.o GpioSunXi.cpp

BuzzerController.o: BuzzerController.cpp BuzzerController.h \
		GpioSunXi.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BuzzerController.o BuzzerController.cpp

PanelWidget.o: PanelWidget.cpp PanelWidget.h \
		ActivityManager.h \
		ParameterManager.h \
		Result.h \
		Scu.h \
		Utilities.h \
		ui_PanelWidget.h \
		GateController.h \
		Device.h \
		Cryptography.h \
		Settings.h \
		QOnScreenKeyboard/qonscreenkeyboard.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PanelWidget.o PanelWidget.cpp

QFocusableLineEdit.o: QFocusableLineEdit.cpp QFocusableLineEdit.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QFocusableLineEdit.o QFocusableLineEdit.cpp

QrTicket.o: QrTicket.cpp QrTicket.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		QrKeyStore.h \
		Cryptography.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrTicket.o QrTicket.cpp

QrDbManager.o: QrDbManager.cpp QrDbManager.h \
		Result.h \
		QrTicket.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		Settings.h \
		Utilities.h \
		ActivityManager.h \
		ParameterManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrDbManager.o QrDbManager.cpp

QrServerManager.o: QrServerManager.cpp QrServerManager.h \
		ActivityManager.h \
		ParameterManager.h \
		Result.h \
		QrDbManager.h \
		QrTicket.h \
		QrCode.h \
		Barcode.h \
		BarcodeType.h \
		Utilities.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrServerManager.o QrServerManager.cpp

QrKeyStore.o: QrKeyStore.cpp QrKeyStore.h \
		Cryptography.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o QrKeyStore.o QrKeyStore.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_HoneywellBarcodeReader.o: moc_HoneywellBarcodeReader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_HoneywellBarcodeReader.o moc_HoneywellBarcodeReader.cpp

moc_Scu.o: moc_Scu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Scu.o moc_Scu.cpp

moc_ParameterManager.o: moc_ParameterManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ParameterManager.o moc_ParameterManager.cpp

moc_MetroBusiness.o: moc_MetroBusiness.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MetroBusiness.o moc_MetroBusiness.cpp

moc_GateController.o: moc_GateController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GateController.o moc_GateController.cpp

moc_PanelWidget.o: moc_PanelWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PanelWidget.o moc_PanelWidget.cpp

moc_QFocusableLineEdit.o: moc_QFocusableLineEdit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QFocusableLineEdit.o moc_QFocusableLineEdit.cpp

moc_QrServerManager.o: moc_QrServerManager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_QrServerManager.o moc_QrServerManager.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/root/ || $(MKDIR) $(INSTALL_ROOT)/root/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/root/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/root/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/root/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/root/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

